package pojo;
// Generated Oct 5, 2022 7:48:08 PM by Hibernate Tools 4.3.1

import DataKaryawan.Data_Karyawan;
import java.util.List;
import javax.faces.bean.ManagedBean;




/**
 * TblKaryawan generated by hbm2java
 */
@ManagedBean
public class TblKaryawan  implements java.io.Serializable {


        private Integer idKaryawan;
     private String nomorKaryawan;
     private String jabatan;
     private String namaKaryawan;
     private String tanggalLahir;
     private String jenisKelamin;
     private String alamat;
     
     public void save_karyawan()
         {
        Data_Karyawan add = new Data_Karyawan();
        add.add_Karyawan(this);
    }
     
     public List<TblKaryawan> getAllRecords()
    {
        Data_Karyawan stud = new Data_Karyawan();
        List<TblKaryawan > iStud = stud.retrieveTblKaryawan();
        return iStud;
    }
     
    public String getById()
    {
        String id_karyawan = Integer.toString(idKaryawan);
        Data_Karyawan stud = new Data_Karyawan();
        List<TblKaryawan> stud1 = stud.getbyID(id_karyawan);
        try {
            if (stud1 != null) {
                idKaryawan = stud1.get(0).idKaryawan;
                nomorKaryawan = stud1.get(0).nomorKaryawan;
                jabatan = stud1.get(0).jabatan;
                namaKaryawan = stud1.get(0).namaKaryawan;
                tanggalLahir = stud1.get(0).tanggalLahir;
                jenisKelamin = stud1.get(0).jenisKelamin;
                alamat = stud1.get(0).alamat;
                return "Data Karyawan";
            }
        } catch (Exception e) {
            System.out.println(e);
        }
        return "Failed Search Data Karyawan";
    }
     public String editKaryawan()
    {
        Data_Karyawan stud = new Data_Karyawan();
        stud.editKaryawan(this);
        idKaryawan = 0;
        nomorKaryawan = "";
       jabatan = "";
        namaKaryawan = "";
        tanggalLahir = null;
        jenisKelamin = "";
        alamat = "";
        return "Data Karyawan";
    }
    
    public String deleteKaryawan()
    {
        //String id_siswa = Integer.toString(idSiswa);
        Data_Karyawan stud = new Data_Karyawan();
        stud.deleteKaryawan (idKaryawan);
        idKaryawan = 0;
        nomorKaryawan = "";
        jabatan = "";
        namaKaryawan = "";
        tanggalLahir = null;
        jenisKelamin = "";
        alamat = "";
        return "Data Karyawan";
    }

    public TblKaryawan() {
    }


    public TblKaryawan(int idKaryawan,String nomorKaryawan, String jabatan, String namaKaryawan, String tanggalLahir, String jenisKelamin, String alamat) {
       this.idKaryawan = idKaryawan;
       this.nomorKaryawan = nomorKaryawan;
       this.jabatan = jabatan;
       this.namaKaryawan = namaKaryawan;
       this.tanggalLahir = tanggalLahir;
       this.jenisKelamin = jenisKelamin;
       this.alamat = alamat;
    }
   
    public Integer getIdKaryawan() {
        return this.idKaryawan;
    }
    
    public void setIdKaryawan(Integer idKaryawan) {
        this.idKaryawan = idKaryawan;
    }
    public String getNomorKaryawan() {
        return this.nomorKaryawan;
    }
    
    public void setNomorKaryawan(String nomorKaryawan) {
        this.nomorKaryawan = nomorKaryawan;
    }
    public String getJabatan() {
        return this.jabatan;
    }
    
    public void setJabatan(String jabatan) {
        this.jabatan = jabatan;
    }
    public String getNamaKaryawan() {
        return this.namaKaryawan;
    }
    
    public void setNamaKaryawan(String namaKaryawan) {
        this.namaKaryawan = namaKaryawan;
    }
    public String getTanggalLahir() {
        return this.tanggalLahir;
    }
    
    public void setTanggalLahir(String tanggalLahir) {
        this.tanggalLahir = tanggalLahir;
    }
    public String getJenisKelamin() {
        return this.jenisKelamin;
    }
    
    public void setJenisKelamin(String jenisKelamin) {
        this.jenisKelamin = jenisKelamin;
    }
    public String getAlamat() {
        return this.alamat;
    }
    
    public void setAlamat(String alamat) {
        this.alamat = alamat;
    }




}


